#!/bin/bash 

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo -ne "Stopping Network Manager..."
service network-manager stop &> /dev/null
sleep 1
tput cuf $(($(tput cols)-36))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput setaf 7
echo "]     "
echo -ne "Taking down wireless interface..."
ifconfig wlan1 down
tput cuf $(($(tput cols)-42))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput setaf 7
echo -ne "]     "
echo -ne "Configuring ad-hoc network..."
iwconfig wlan1 mode ad-hoc
iwconfig wlan1 channel 8
iwconfig wlan1 ap f8:d1:11:64:5e:a8
iwconfig wlan1 essid groep8
iwconfig wlan1 key 1234567890
tput cuf $(($(tput cols)-38))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput setaf 7
echo "]     "
echo -ne "Starting wireless network interface..."
ifconfig wlan1 192.168.5.3 up
tput cuf $(($(tput cols)-47))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput setaf 7
echo "]     "
echo -ne "Setting up correct routing paths..."
route add -net 228.0.0.0/8 dev wlan1
tput cuf $(($(tput cols)-44))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput setaf 7
echo "]     "
echo "You are now connected to the ad-hoc network with IP address 192.168.5.3"
